[package]
name = "state_to_region_topic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
flate2 = "1.0.30"
parquet = "52.2.0"
arrow = "52.2.0"
